name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: make sync
      - run: make check
